#!/usr/sbin/nft -f 
 
flush ruleset 
 
table inet filter { 
 
    chain input { 
        type filter hook input priority filter; policy drop; 
 
        # Loopback 
        iif lo accept 
 
        # Conexões estabelecidas 
        ct state established,related accept 
 
        # ICMP 
        ip protocol icmp accept 
        ip6 nexthdr ipv6-icmp accept 
 
        # Docker 
        iifname "docker0" accept 
 
        # Libvirt 
        iifname "virbr0" accept 
 
        # Waydroid (DNS/DHCP do container) 
        iifname "waydroid0" accept 
 
        # SSH 
        tcp dport 22 accept 
 
        # Aria2 somente localhost 
        iif lo tcp dport 6800 accept 
 
        # Hydra somente localhost 
        iif lo tcp dport 8084 accept 
 
        counter drop 
    } 
 
    chain forward { 
        type filter hook forward priority filter; policy drop; 
 
        ct state established,related accept 
 
        # Docker 
        iifname "docker0" accept 
        oifname "docker0" accept 
 
        # Libvirt 
        iifname "virbr0" accept 
        oifname "virbr0" accept 
 
        # Waydroid 
        iifname "waydroid0" accept 
        oifname "waydroid0" accept 
    } 
 
    chain output { 
        type filter hook output priority filter; policy accept; 
    } 
}
